name: "publish"

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish-electron:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "macos-latest"
          - platform: "windows-latest"
          - platform: "ubuntu-22.04"

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: "electron-app/package-lock.json"

      - name: install dependencies
        working-directory: electron-app
        run: npm install

      - name: build and release
        working-directory: electron-app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ "${{ matrix.platform }}" == "windows-latest" ]; then
            npm run build
          else
            npm run build
          fi
